services:
  apigateaway:
    image: nginx:1.27-alpine
    container_name: apigateaway
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      edge:
        aliases:
          - apigateaway
    
networks:
  edge:
    external: true