
services:
  course_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - course_db_data:/var/lib/postgresql/course_db_data
    # ports:
    #   - "5433:5432"
    networks: [appnet]


  adminer:
    image: adminer
    depends_on: [course_db]
    environment:
      ADMINER_DEFAULT_SERVER: course_db
    # ports:
    #   - "8081:8080"
    networks: [appnet]

  course_service:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@course_db:5432/course}
      DATABSE_SYNC_URL: ${DATABASE_SYNC_URL:-postgresql://postgres:postgres@course_db:5432/course}
      APP_PORT: ${APP_PORT:-8000}
    depends_on: [course_db]
    expose:
      - "8000"
    networks:
      - appnet
      - edge

volumes:
  course_db_data:

networks:
  appnet:
    driver: bridge
  edge:
    external: true